# Generated by Django 5.1.6 on 2025-02-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=400)),
                ('completed', models.BooleanField(default=False)),
                ('banner', models.ImageField(blank=True, default='fallback.png', upload_to='')),
            ],
        ),
    ]
